config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :lectures
  devise_for :users, controllers: {
    omniauth_callbacks: 'omniauth_callbacks',
    :registrations => :registrations
  }
  resources :users, only: [:show, :index]
  root 'pages#search'
  resources :questions do
    resources :answers, only: [:create, :new]
    resources :charges, only: [:create, :new]
    member do
      post :accept
    end
  end
  get 'about' => 'pages#about'
  get 'contact' => 'pages#contact'
  get 'faq' => 'pages#faq'
  # get 'users/auth/stripe_connect/callback', to: 'stripe_connect#create'

end

app/models/question.rb
class Question < ApplicationRecord
  validates :query, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 0.01 }

  belongs_to :sender, class_name: 'User'
  belongs_to :recipient, class_name: 'User'
  has_one :answer, :dependent => :destroy
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]

  def index
    @questions = Question.order(updated_at: :desc).page(params[:page]).per(10)
  end

  def show
    @question = Question.find(params[:id])
    if Answer.exists?(question_id: @question.id)
      @answer = Answer.where(question_id: @question.id)
    else
      @answer = @question.build_answer
    end
  end

  def accept
    @question = Question.find(params[:id])
    @question.state = 'accepted'
    # byebug
    @question.save!
    flash[:notice] = 'You have accepted this question. Sender has been notified'
    redirect_to question_path(@question)
  end

  def new
    @question = Question.new
  end
  
  def create
    @question = Question.new(question_params)
    @question.sender = current_user
    @question.state = 'pending'

    if @question.save
      flash[:notice] = 'Question has been created.'
      redirect_to @question
    else
      flash.now[:alert] = 'Question has not been created.'
      @user = @question.recipient
      render 'users/show'
    end
  end

  # def update
  #   @question = Question.find(params[:id])
  #   @question.update(question_params)

  #   flash[:notice] = 'Question has been updated.'
  #   redirect_to @question
  # end

  private

  def question_params
    params.require(:question).permit(:query, :recipient_id, :price)
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def has_answer(question)
    if !question.answer.nil?
      truncate(strip_tags(question.answer.response), length: 100,
        separator: ' '){ link_to "(read more)", question_path(question) }
    else
      "This question hasnt been answered yet."
    end
  end
end

app/views/questions/_form.html.erb
<h1>Ask me anything...</h1>

<%= simple_form_for @question do |f| %>
  <%= f.input :query, label: "Your Question" %>
  <%= f.input :price, label: "Amount (USD)" %>
  <%= f.association :recipient, as: :hidden, value: @user.id %>
  <%= f.button :submit %>
<% end %>

app/views/questions/index.html.slim
h1 Questions
- @questions.each do |question|
  .question
    h4= link_to question.query, question
    p.image= image_tag question.recipient.profile_pic_url(:thumb)
    strong To: 
    = link_to question.recipient.name, user_path(question.recipient)
    p
    strong Amount: 
    = number_to_currency(question.price)
    p= has_answer(question)
= paginate @questions

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= simple_form_for @question do |f| %>
  <%= f.input :query, label: "Your Question" %>
  <%= f.association :recipient, label_method: :email, value_method: :id %>
  <%= f.button :submit %>
<% end %>

app/views/questions/show.html.slim
.question
  h3= @question.query
  / p From 
  / = link_to @question.sender.name, @question.sender
  .image= image_tag @question.recipient.profile_pic_url(:thumb)
  = link_to @question.recipient.name, @question.recipient

  p #{@question.state} for
  p.price= number_to_currency(@question.price)

  - if @question.recipient == current_user
    - if @question.state == 'pending'
      = link_to "Accept", accept_question_path(@question), method: :post
    - if @question.state == 'accepted'
      = link_to ">Answer this question<", new_question_answer_path(@question)

  - if @question.answer.response
    .trix-content= sanitize(@question.answer.response)
  - else
    p This question has not been answered yet.

  - if @question.sender == current_user && @question.state == 'accepted'
    = render "charges/charge", question: @question