config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :lectures
  devise_for :users, controllers: {
    omniauth_callbacks: 'omniauth_callbacks',
    :registrations => :registrations
  }
  resources :users, only: [:show, :index]
  root 'pages#search'
  resources :questions do
    resources :answers, only: [:create, :new]
    resources :charges, only: [:create, :new]
    member do
      post :accept
    end
  end
  get 'about' => 'pages#about'
  get 'contact' => 'pages#contact'
  get 'faq' => 'pages#faq'
  # get 'users/auth/stripe_connect/callback', to: 'stripe_connect#create'

end

app/models/lecture.rb
class Lecture < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
end

app/controllers/lectures_controller.rb
class LecturesController < ApplicationController
  before_action :set_lecture, only: [:show, :edit, :update, :destroy]

  # GET /lectures
  # GET /lectures.json
  def index
    @lectures = Lecture.order(updated_at: :desc).page(params[:page]).per(10)
  end

  # GET /lectures/1
  # GET /lectures/1.json
  def show
  end

  # GET /lectures/new
  def new
    @lecture = Lecture.new
  end

  # GET /lectures/1/edit
  def edit
  end

  # POST /lectures
  # POST /lectures.json
  def create
    @lecture = Lecture.new(lecture_params)
    @lecture.user = current_user

    respond_to do |format|
      if @lecture.save
        format.html { redirect_to @lecture, notice: 'Lecture was successfully created.' }
        format.json { render :show, status: :created, location: @lecture }
      else
        format.html { render :new }
        format.json { render json: @lecture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lectures/1
  # PATCH/PUT /lectures/1.json
  def update
    respond_to do |format|
      if @lecture.update(lecture_params)
        format.html { redirect_to @lecture, notice: 'Lecture was successfully updated.' }
        format.json { render :show, status: :ok, location: @lecture }
      else
        format.html { render :edit }
        format.json { render json: @lecture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lectures/1
  # DELETE /lectures/1.json
  def destroy
    @lecture.destroy
    respond_to do |format|
      format.html { redirect_to lectures_url, notice: 'Lecture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lecture
      @lecture = Lecture.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lecture_params
      params.require(:lecture).permit(:content, :title)
    end
end

app/helpers/lectures_helper.rb
module LecturesHelper
end

app/views/lectures/_form.html.erb
<%= simple_form_for(@lecture) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :content, label: false, as: :trix_editor %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/lectures/edit.html.erb
<h1>Editing Lecture</h1>

<%= render 'form', lecture: @lecture %>

<%= link_to 'Show', @lecture %> |
<%= link_to 'Back', lectures_path %>

app/views/lectures/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Articles</h1>

<%= link_to 'New Article', new_lecture_path %>

<% @lectures.each do |lecture| %>
  <div class="question">
    <h4><%= link_to lecture.title, lecture %></h4>
    <p><%= image_tag lecture.user.profile_pic_url(:thumb) %></p>
    <p><%= link_to lecture.user.name, user_path(lecture.user) %></p>
    <p><%= truncate(strip_tags(lecture.content), length: 200,
      separator: ' '){ link_to "(read more)", lecture } %></p>
  </div>
<% end %>

app/views/lectures/new.html.erb
<h1>New Article</h1>

<%= render 'form', lecture: @lecture %>

<%= link_to 'Back', lectures_path %>

app/views/lectures/show.html.erb
<p id="notice"><%= notice %></p>
<div class="question">
  <h3><%= @lecture.title %></h3>
  <%= image_tag @lecture.user.profile_pic_url(:thumb) %>
  <p><%= link_to(@lecture.user.name, @lecture.user) %></p>
  <p class="trix-content article"><%= strip_tags(sanitize(@lecture.content)) %></p>
</div>

<%# link_to 'Edit', edit_lecture_path(@lecture) %> 
<%# link_to 'Back', lectures_path %>