config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :lectures
  devise_for :users, controllers: {
    omniauth_callbacks: 'omniauth_callbacks',
    :registrations => :registrations
  }
  resources :users, only: [:show, :index]
  root 'pages#search'
  resources :questions do
    resources :answers, only: [:create, :new]
    resources :charges, only: [:create, :new]
    member do
      post :accept
    end
  end
  get 'about' => 'pages#about'
  get 'contact' => 'pages#contact'
  get 'faq' => 'pages#faq'
  # get 'users/auth/stripe_connect/callback', to: 'stripe_connect#create'

end

app/models/charge.rb
class Charge < ApplicationRecord
  belongs_to :question
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
  end

  def create
    # byebug
    @question = Question.find(params[:question_id])
    @charge = Charge.create(question: @question)
    # Amount in cents
    @amount = 500

    customer = Stripe::Customer.create({
      email: params[:stripeEmail],
      source: params[:stripeToken]
    })

    token = Stripe::Token.create({
      :customer => customer.id,
    }, {:stripe_account => @question.recipient.stripe_id})

    # save customer.id to database?

    transaction = Stripe::Charge.create({
      amount: @amount,
      application_fee_amount: 100,
      currency: 'usd',
      source: token.id
      }, stripe_account: @question.recipient.stripe_id
    )
    # byebug
    if transaction.paid?
      @charge.paid = transaction.paid
      @charge.total = transaction.amount
      @charge.fee_charged = transaction.application_fee_amount
      @charge.stripe_charge_id = transaction.id
      @charge.save!
    end

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/views/charges/_charge.html.erb
<%= form_tag question_charges_path(@question) do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Amount: <%= number_to_currency(@question.price) %></span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= ENV['PUBLISHABLE_KEY'] %>"
          data-email="<%= @question.sender.email %>"
          data-description="Thy Scholar Payment"
          data-locale="auto"></script>
<% end %>

app/views/charges/create.html.erb
<h2>Thanks, you paid <%= number_to_currency(@charge.total) %>!</h2>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Amount: $5.00</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="500"
          data-locale="auto"></script>
<% end %>