config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :lectures
  devise_for :users, controllers: {
    omniauth_callbacks: 'omniauth_callbacks',
    :registrations => :registrations
  }
  resources :users, only: [:show, :index]
  root 'pages#search'
  resources :questions do
    resources :answers, only: [:create, :new]
    resources :charges, only: [:create, :new]
    member do
      post :accept
    end
  end
  get 'about' => 'pages#about'
  get 'contact' => 'pages#contact'
  get 'faq' => 'pages#faq'
  # get 'users/auth/stripe_connect/callback', to: 'stripe_connect#create'

end

app/views/layouts/_footer.html.slim
footer
  ul
    li= link_to "About", about_path
    | |
    li= link_to "Contact", contact_path
    | |
    li= link_to "FAQ", faq_path
  p Copyright &copy; 2019 Thy Scholar | All Rights Reserved

app/views/layouts/application.html.slim
doctype html
html
  head
    title ThyScholar
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  body
    h2=link_to "Thy Scholar", root_path
    div.burger-holder
      li.hamb= link_to("javascript:void(0);", :onclick => "burgerMenu(this)")
        .bar1
        .bar2
        .bar3
    nav#main_menu
      ul
        li= link_to "Q&A", questions_path
        li= link_to "Articles", lectures_path
        li= link_to "Users", users_path
        - if user_signed_in?
          li= link_to "My Profile", user_path(current_user.id)
          li= link_to "Sign Out", destroy_user_session_path, method: :delete
          li Logged in: #{current_user.name}
        - else
          li= link_to "Sign Up", new_user_registration_path
          li= link_to "Log In", new_user_session_path
    - flash.each do |key, message|
      = content_tag :p, message, class: key
    .global-container
      main class=[controller.controller_name]
        == yield
    =render "layouts/footer"